export const en = {
    gnb: {
        placeholder: 'Search for buddies',
        sAria: 'search',
        sTAria: 'open search',
        pAria: 'profile menu',
        book: 'Book Marks',
        chat: 'Chats',
        alert: 'Alert',
        dear: 'Dear',
        mypage: 'MyPage',
        logout: 'Logout',
    },
    ttt: 'Hot Travel This Week',
    find: 'Find travel companions to join me',
    result: 'Travel found:',
    count: '',
    lookfor: 'only active listings',
    filter: {
        where: 'Where are we going?',
        date: 'When are we going?',
        theme: 'Travel theme',
        memb: 'Group size',
        SA: 'Gender/Age',
        reset: 'Reset',
        apply: 'Apply',
        gender: 'Gender',
        age: 'Age',
    },
    post: 'Submit',
    edit: 'Edit',
    posting: 'Posting',
    editting: 'Editing',
    close: 'Close',
    errorLoading: 'Error Loading Post',
    tryagain: 'please try agin later',
};
