export const ko = {
    gnb: {
        placeholder: '동행 키워드를 검색해 보세요',
        sAria: '검색',
        sTAria: '검색창 열기',
        pAria: '프로필 메뉴',
        book: '찜한 동행',
        chat: '채팅 목록',
        alert: '알림',
        dear: '님',
        mypage: '마이 페이지',
        logout: '로그 아웃',
    },
    ttt: '이번 주 Hot한 동행',
    find: '나와 함께 할 동행 찾기',
    result: '검색된 동행',
    count: '개',
    lookfor: '동행 구함만 보기',
    filter: {
        where: '동행지는 어디인가요?',
        date: '날짜는 언제인가요?',
        theme: '동행 테마',
        memb: '인원 수',
        SA: '성별/나이',
        reset: '초기화',
        apply: '적용',
        gender: '성별',
        age: '나이',
    },

    post: '등록',
    edit: '수정',
    posting: '등록중 ...',
    editting: '수정중 ...',
    close: '닫기',
    errorLoading: '글을 불러오는데 실패 했어요.',
    tryagain: '잠시 후 다시 시도해 주세요',
};
