name: Synchronize to forked repo
on:
    workflow_run:
        workflows:
            - 'Push Validation'
        types:
            - completed

jobs:
    sync:
        name: Sync forked repo
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.FORKED_REPO_SYNC }}
                  fetch-depth: 0
                  ref: main

            - name: Add remote-url
              run: |
                  git remote add forked-repo https://jungdadak:${{ secrets.FORKED_REPO_SYNC }}@github.com/jungdadak/sprint1.git
                  git config user.name jungdadak
                  git config user.email junghyun21110@naver.com

            - name: Checkout main
              run: |
                  git checkout -b main

            - name: Push changes to forked-repo
              run: |
                  git push -f forked-repo main:main

            - name: Clean up
              run: |
                  git remote remove forked-repo
